---
deployment:
  tasks:
    - export PROJECTPATH=/home8/thedurbarschoole/repositories/durbarwebsite
    - export DEPLOYPATH=/home8/thedurbarschoole/public_html

    # Go to project directory
    - cd $PROJECTPATH

    - echo "Installing dependencies..."
    - /opt/cpanel/ea-nodejs20/bin/npm install

    - echo "Building React..."
    - /opt/cpanel/ea-nodejs20/bin/npm run build

    - echo "Cleaning old frontend files but keeping backend..."
    # Delete everything *except* api, api-backend, .htaccess
    - find $DEPLOYPATH -mindepth 1 -maxdepth 1 \
        ! -name 'api' \
        ! -name 'api-backend' \
        ! -name '.htaccess' \
        -exec rm -rf {} +

    - echo "Deploying new build..."
    - cp -R $PROJECTPATH/build/* $DEPLOYPATH/

    - echo "Deployment complete!"
